FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /workspace

COPY requirements-jupyter.txt /tmp/requirements-jupyter.txt

RUN pip install --no-cache-dir -r /tmp/requirements-jupyter.txt
